export default Object.fromEntries([
    'blockColors',
    'cascadeProcedureColors',
    'disableExpandables',
    'hexagonalRoundness',
    'mergeOperators',
    'outputBubbleAutoTyping',
    'paintMultiTool',
    'paintScrollZoom',
    'soundDisplayDetail',
    'showExtensionIds',
    'splashModal',
    'swatches',
    'test',
    'vmDebug',
].map(v => [v, require(`./settings/${v}/${v}.jsx`).default]))